// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLUfrzCBsKvnr1WDZZdIEOHlMdHvO574U',
    appId: '1:928230208191:web:2e14b3b4b8cce3b4978c0a',
    messagingSenderId: '928230208191',
    projectId: 'ai-chat-app-339ca',
    authDomain: 'ai-chat-app-339ca.firebaseapp.com',
    storageBucket: 'ai-chat-app-339ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkcNtsPN7njjo0Zvuas1nKoqnLFt4fsWQ',
    appId: '1:928230208191:android:1c81182a9f414b62978c0a',
    messagingSenderId: '928230208191',
    projectId: 'ai-chat-app-339ca',
    storageBucket: 'ai-chat-app-339ca.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHGAReP9_Cd78dy6u4nsnor5Nap2fHMac',
    appId: '1:928230208191:ios:0dd43b41fe8dca04978c0a',
    messagingSenderId: '928230208191',
    projectId: 'ai-chat-app-339ca',
    storageBucket: 'ai-chat-app-339ca.firebasestorage.app',
    androidClientId: '928230208191-6j5f5hnmmpqfgpd5lopfj3ui10fi25uv.apps.googleusercontent.com',
    iosClientId: '928230208191-c7anflsvceif9adagls0qfbcn0cqb92q.apps.googleusercontent.com',
    iosBundleId: 'com.meet.nexora',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHGAReP9_Cd78dy6u4nsnor5Nap2fHMac',
    appId: '1:928230208191:ios:0dd43b41fe8dca04978c0a',
    messagingSenderId: '928230208191',
    projectId: 'ai-chat-app-339ca',
    storageBucket: 'ai-chat-app-339ca.firebasestorage.app',
    androidClientId: '928230208191-6j5f5hnmmpqfgpd5lopfj3ui10fi25uv.apps.googleusercontent.com',
    iosClientId: '928230208191-c7anflsvceif9adagls0qfbcn0cqb92q.apps.googleusercontent.com',
    iosBundleId: 'com.meet.nexora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLUfrzCBsKvnr1WDZZdIEOHlMdHvO574U',
    appId: '1:928230208191:web:f200b2423c226742978c0a',
    messagingSenderId: '928230208191',
    projectId: 'ai-chat-app-339ca',
    authDomain: 'ai-chat-app-339ca.firebaseapp.com',
    storageBucket: 'ai-chat-app-339ca.firebasestorage.app',
  );

}